### Задача:
Для заданной матрицы размером 8 на 8 найти такие k, что k-я строка матрицы совпадает с k-м столбцом.

In [1]:
import numpy as np

In [2]:
matrix = np.matrix('-1 2 3 4 5 6 7 8;'
                   '2 3 4 5 6 7 8 5;'
                   '3 4 5 6 7 8 9 5;'
                   '4 5 6 7 8 9 0 5;'
                   '5 6 7 8 9 0 1 5;'
                   '6 7 8 9 0 1 2 5;'
                   '7 8 9 0 1 2 -3 4;'
                   '8 9 0 1 2 3 4 5')

In [3]:
print(matrix)

[[-1  2  3  4  5  6  7  8]
 [ 2  3  4  5  6  7  8  5]
 [ 3  4  5  6  7  8  9  5]
 [ 4  5  6  7  8  9  0  5]
 [ 5  6  7  8  9  0  1  5]
 [ 6  7  8  9  0  1  2  5]
 [ 7  8  9  0  1  2 -3  4]
 [ 8  9  0  1  2  3  4  5]]


In [4]:
condition = matrix == matrix.transpose()
condition = condition.prod(axis=0)
condition = np.ravel(np.where(condition == 1, True, False))
k = np.arange(condition.size)[condition]

print(f"Значения k, такие, что k-я строка "
      f"матрицы совпадает с k-м столбцом: {k}")

Значения k, такие, что k-я строка матрицы совпадает с k-м столбцом: [0 6]


### Задача:
Найти сумму элементов в тех строках, которые содержат хотя бы один отрицательный элемент.

In [5]:
condition = matrix < 0
condition = condition.sum(axis=0)
condition = np.ravel(np.where(condition == 1, True, False))
ans = np.ravel(matrix[condition].sum(axis = 1))
print(f"Суммы элементов в строках, которые содержат "
      f"хотя бы один отрицательный элемент: {ans}")

Суммы элементов в строках, которые содержат хотя бы один отрицательный элемент: [34 28]
