

# Лабораторная работа 3.2. Знакомство с NumPy
Библиотека NumPy -- быстрая библиотека для математики в Python, основная структура данных -- массив `numpy.array`:

![](https://media.giphy.com/media/3o7btPCcdNniyf0ArS/giphy.gif)

In [1]:
# подключение модуля numpy под именем np
import numpy as np

In [2]:
# основная структура данных - массив
a = np.array([1, 2, 3, 4, 5])
b = np.array([0.1, 0.2, 0.3, 0.4, 0.5])

print("a =", a)
print("b =", b)

a = [1 2 3 4 5]
b = [0.1 0.2 0.3 0.4 0.5]


Создайте массив с 5 любыми числами:

In [3]:
c = np.random.randint(1, 10, 5)
c

array([6, 8, 3, 5, 2])

Арифметические операции, в отличие от операций над списками, применяются поэлементно:

In [4]:
list1 = [1, 2, 3]
array1 = np.array([1, 2, 3])

print("list1:", list1)
print('\tlist1 * 3:', list1 * 3)
print('\tlist1 + [1]:', list1 + [1])

print('array1:', array1)
print('\tarray1 * 3:', array1 * 3)
print('\tarray1 + 1:', array1 + 1)

list1: [1, 2, 3]
	list1 * 3: [1, 2, 3, 1, 2, 3, 1, 2, 3]
	list1 + [1]: [1, 2, 3, 1]
array1: [1 2 3]
	array1 * 3: [3 6 9]
	array1 + 1: [2 3 4]


Создайте массив из 5 чисел. Возведите каждый элемент массива в степень 3

In [5]:
c = np.random.randint(1, 10, 5)
print(c)
print(f"c^3: {c**3}")

[4 5 6 8 1]
c^3: [ 64 125 216 512   1]


Если в операции участвуют $2$ массива (по умолчанию -- одинакового размера), операции считаются для соответствующих пар:

In [6]:
print("a + b =", a + b)
print("a * b =", a * b)

a + b = [1.1 2.2 3.3 4.4 5.5]
a * b = [0.1 0.4 0.9 1.6 2.5]


In [7]:
# вот это разность
print("a - b =", a - b)

# вот это деление
print("a / b =", a / b)

# вот это целочисленное деление
print("a // b =", a // b)

# вот это квадрат
print("a ** 2 =", a ** 2)

a - b = [0.9 1.8 2.7 3.6 4.5]
a / b = [10. 10. 10. 10. 10.]
a // b = [ 9.  9. 10.  9. 10.]
a ** 2 = [ 1  4  9 16 25]


 Создайте два массива одинаковой длины. Выведите массив, полученный делением одного массива на другой.

In [8]:
d = np.random.randint(1, 10, 5)
e = np.random.randint(1, 10, 5)
print(f"d / e = {d/e}")

d / e = [5.         0.33333333 1.28571429 4.         0.55555556]


#### *Л — логика*
К элементам массива можно применять логические операции.

Возвращаемое значение -- массив, содержащий результаты вычислений для каждого элемента (`True` -- "да" или `False` -- "нет"):

In [9]:
print("a =", a)
print("\ta > 1: ", a > 1)
print("\nb =", b)
print("\tb < 0.5:  ", b < 0.5)

print("\nОдновременная проверка условий:")
print("\t(a > 1) & (b < 0.5):  ", (a>1) & (b < 0.5))
print("А вот это проверяет, что a > 1 ИЛИ b < 0.5:  ", (a > 1) | (b < 0.5))

a = [1 2 3 4 5]
	a > 1:  [False  True  True  True  True]

b = [0.1 0.2 0.3 0.4 0.5]
	b < 0.5:   [ True  True  True  True False]

Одновременная проверка условий:
	(a > 1) & (b < 0.5):   [False  True  True  True False]
А вот это проверяет, что a > 1 ИЛИ b < 0.5:   [ True  True  True  True  True]


Создайте 2 массива из 5 элементов. Проверьте условие "Элементы первого массива меньше 6, элементы второго массива делятся на 3"

In [10]:
d = np.random.randint(1, 10, 5)
e = np.random.randint(1, 10, 5)
log1 = d < 6
log2 = e % 3 == 0
print(d)
print(e)
print(log1)
print(log2)

[4 5 8 6 1]
[4 8 2 3 8]
[ True  True False False  True]
[False False False  True False]


Теперь проверьте условие "Элементы первого массива делятся на 2 или элементы второго массива больше 2"

In [11]:
log3 = np.logical_or(d % 2 == 0, e > 2)
print(log3)

[ True  True  True  True  True]


Зачем это нужно? Чтобы выбирать элементы массива, удовлетворяющие какому-нибудь условию:

In [12]:
print("a =", a)
print("a > 2:", a > 2)
# индексация - выбираем элементы из массива в тех позициях, где True
print("a[a > 2]:", a[a > 2])

a = [1 2 3 4 5]
a > 2: [False False  True  True  True]
a[a > 2]: [3 4 5]


Создайте массив с элементами от 1 до 20. Выведите все элементы, которые больше 5 и не делятся на 2

Подсказка: создать массив можно с помощью функции np.arange(), действие которой аналогично функции range, которую вы уже знаете.

In [13]:
d = np.arange(1, 21)
print(d)
d = d[np.logical_and(d >5, d % 2 != 0)]
print(d)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 7  9 11 13 15 17 19]


#### А ещё NumPy умеет...

Все операции NumPy оптимизированы для быстрых вычислений над целыми массивами чисел и в методах `np.array` реализовано множество функций, которые могут вам понадобиться:

In [14]:
# теперь можно считать средний размер котиков в одну строку!
print("np.mean(a) =", np.mean(a))
# минимальный элемент
print("np.min(a) =", np.min(a))
# индекс минимального элемента
print("np.argmin(a) =", np.argmin(a))
# вывести значения массива без дубликатов
print("np.unique(['male', 'male', 'female', 'female', 'male']) =", np.unique(['male', 'male', 'female', 'female', 'male']))

# и ещё много всяких методов
# Google в помощь

np.mean(a) = 3.0
np.min(a) = 1
np.argmin(a) = 0
np.unique(['male', 'male', 'female', 'female', 'male']) = ['female' 'male']


---

---

Пора еще немного потренироваться с NumPy.

Выполните операции, перечисленные ниже:

In [15]:
print("Разность между a и b:", a - b
     )
print("Квадраты элементов b:", b**2
     )
print("Половины произведений элементов массивов a и b:", (a * b) / 2
     )

print()
print("Максимальный элемент b:", np.max(b)
     )
print("Сумма элементов массива b:", np.sum(b)
     )
print("Индекс максимального элемента b:", np.argmax(b)
     )

Разность между a и b: [0.9 1.8 2.7 3.6 4.5]
Квадраты элементов b: [0.01 0.04 0.09 0.16 0.25]
Половины произведений элементов массивов a и b: [0.05 0.2  0.45 0.8  1.25]

Максимальный элемент b: 0.5
Сумма элементов массива b: 1.5
Индекс максимального элемента b: 4


 Задайте два массива: [5, 2, 3, 12, 4, 5]   и   ['f', 'o', 'o', 'b', 'a', 'r']

Выведите буквы из второго массива, индексы которых соответствуют индексам чисел из первого массива, которые больше 1, меньше 5 и делятся на 2

In [16]:
d = np.array([5, 2, 3, 12, 4, 5])
e = np.array(['f', 'o', 'o', 'b', 'a', 'r'])
log1 = np.logical_and(d > 1, d < 5, d % 2 == 0)
print(log1)
print(e[log1])

[False  True  True False  True False]
['o' 'o' 'a']
